openapi: 3.0.3
info:
  title: Music Metadata Service - Artist API
  version: 1.0.0
  description: API for managing and querying music artist metadata
tags:
  - name: Artist
    description: Operations related to artists

paths:
  /artists/artist-of-the-day:
    get:
      tags:
        - Artist
      summary: Get today's featured musicmetadata
      operationId: getArtistOfTheDay
      responses:
        '200':
          description: Successfully returned featured musicmetadata
          content:
            application/json:
              schema:
                $ref: 'artist-dto.yaml#/components/schemas/ArtistResponse'
        '404':
          description: No artists available
          content:
            application/json:
              schema:
                $ref: 'artist-dto.yaml#/components/schemas/ErrorResponse'

  /artists/{artistId}/tracks:
    get:
      tags:
        - Artist
      summary: Get tracks for an musicmetadata UUID
      operationId: getArtistTracks
      parameters:
        - name: artistId
          in: path
          required: true
          description: The unique identifier of the musicmetadata.
          schema:
            type: string
            format: uuid
        - name: page
          in: query
          description: Page number (0-indexed)
          required: false
          schema:
            type: integer
            default: 0
            minimum: 0
        - name: size
          in: query
          description: Items per page
          required: false
          schema:
              type: integer
              default: 20
              minimum: 1
              maximum: 100

      responses:
        '200':
          description: Successfully returned tracks by musicmetadata
          content:
            application/json:
              schema:
                $ref: 'artist-dto.yaml#/components/schemas/TrackPageResponse'
        '404':
          description: Artist not found
          content:
            application/json:
              schema:
                $ref: 'artist-dto.yaml#/components/schemas/ErrorResponse'

    post:
      tags:
        - Artist
      summary: Add a new track (Admin only)
      operationId: addTrack
      security:
        - BearerAuth: [ ]
      parameters:
        - name: artistId
          in: path
          required: true
          description: The unique identifier of the musicmetadata.
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'artist-dto.yaml#/components/schemas/TrackRequest'
      responses:
        '201':
          description: Track created successfully
          content:
            application/json:
              schema:
                $ref: 'artist-dto.yaml#/components/schemas/TrackResponse'
        '400':
          description: Invalid input
        '401':
          description: Unauthorized (missing/invalid token)
        '403':
          description: Forbidden (not admin)
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: 'artist-dto.yaml#/components/schemas/ErrorResponse'


  /artists/{artistId}/name:
    patch:
      tags:
        - Artist
      summary: Update musicmetadata name/aliases (Admin only)
      operationId: updateArtistName
      security:
        - BearerAuth: [ ]
      parameters:
        - name: artistId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'artist-dto.yaml#/components/schemas/UpdateArtistNameRequest'
      responses:
        '200':
          description: Artist updated successfully
          content:
            application/json:
              schema:
                $ref: 'artist-dto.yaml#/components/schemas/ArtistResponse'
        '404':
          description: Artist not found
          content:
            application/json:
              schema:
                $ref: 'artist-dto.yaml#/components/schemas/ErrorResponse'
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: 'artist-dto.yaml#/components/schemas/ErrorResponse'